#tomcat端口
#server:
#  port: 9000

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug




spring:
  # Redis 配置
  redis:
    # 本地地址（默认）
    host: localhost
    # 默认端口
    port: 6379
    # 密码（本地无密码，留空）
    password:
    # 数据库索引（Redis 默认有 16 个库，从 0 开始）
    database: 0
    # 连接池配置（推荐，提升性能）
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0
        # 连接等待时间（毫秒）
        max-wait: -1ms